## Different type of Sorting approach with their order of complexity

In [63]:
import numpy as np
dt = np.random.randint(-55, +55, size=40)
import time

### Decorator to record time taken for executing any method

In [28]:
def time_the_method(func):
    def timed(*args, **kwargs):
        ts = time.time()
        result = func(*args, **kwargs)
        te = time.time()
        print(f"Method {func.__name__} takes {(te - ts)*1000} milli seconds to execute")
        return result
    return timed

## Selection Sort
## O($n^2$)

In [26]:
@time_the_method
def selection_sort(arr):
    for i in range(len(arr)):
        min_index = i
        for j in range(i,len(arr)):
            if arr[j] < arr[min_index]:
                min_index = j
            arr[i], arr[min_index] = arr[min_index], arr[i]
    return arr          

In [36]:
selection_sort_output = selection_sort(dt)

Method selection_sort takes 1.7719268798828125 to execute


## Bubble Sort
## O ($n^2$)

In [34]:
@time_the_method
def bubble_sort(arr):
    for i in range(len(arr)):
        for j in range(len(arr) - i - 1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

In [37]:
bubble_sort_output = bubble_sort(dt)

Method bubble_sort takes 0.7479190826416016 milli seconds to execute


## Insertion Sort

## O($n^2$)

In [51]:
@time_the_method
def insertion_sort(arr):
    for i in range(len(arr)-1):
        k = i
        for j in range(i+1):
            if arr[k] > arr[k+1]:
                arr[k], arr[k+1] = arr[k+1], arr[k]
                k-=1
            elif k < 0:
                break
    return arr

In [54]:
insertion_sort_output = insertion_sort(dt)

Method insertion_sort takes 0.8950233459472656 milli seconds to execute


## Merge Sort

## O($nlog(n)$)

In [77]:
def merge_2_sorted_array(ls, l_ls, r_ls):
    i = 0
    j = 0
    for k in range(len(ls)):
        if i < len(l_ls) and j < len(r_ls):
            if l_ls[i] < r_ls[j]:
                ls[k] = l_ls[i]
                i+=1
            else:
                ls[k] = r_ls[j]
                j+=1
        elif i < len(l_ls):
            ls[k] = l_ls[i]
            i+=1
        elif j < len(r_ls):
            ls[k] = r_ls[j]
            j+=1
    return ls

In [78]:
def merge_sort(arr):
    if len(arr) == 2:
        if arr[0] > arr[1]:
            arr[0], arr[1] = arr[1], arr[0]
    elif len(arr) > 2:
        mid = int(len(arr) / 2)
        left_arr = arr[:mid]
        right_arr = arr[mid:]
        left_sorted_array = merge_sort(left_arr)
        right_sorted_array = merge_sort(right_arr)
        arr = merge_2_sorted_array(arr, left_sorted_array, right_sorted_array)
    return arr

In [79]:
merge_sort(dt)

array([-53, -53, -53, -53, -53, -53, -53, -53, -53, -53, -53, -53, -53,
       -53, -53, -53, -53, -53, -53, -53, -53, -53, -53, -53, -53, -53,
       -53, -53, -53, -53, -53, -53, -53, -53, -53, -53, -27, -27, -27,
        29])

In [66]:
dt[:20]

array([  8, -39, -33,  23, -39,  42,  33, -48,  46, -39, -31, -43,  12,
       -43,  37, -38,  -3, -42,  33,  21])

In [67]:
dt[20:]

array([-45, -25, -12,  52, -48,   4,  48,  12,  16, -31, -33, -50,  14,
       -36, -17,  17, -53,  23, -27,  29])